{% set version = "1.0-1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-inum
  version: {{ version|replace("-", "_") }}

source:
  fn: inum_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/inum_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/inum/inum_{{ version }}.tar.gz
  sha256: 3c2f94c13c03607e05817e4859595592068b55e810fed94e29bc181ad248a099

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base >=3.4.0  # r-libcoin requirement
    - r-libcoin >=1.0_0

  run:
    - r-base >=3.4.0  # r-libcoin requirement
    - r-libcoin >=1.0_0

test:
  commands:
    - $R -e "library('inum')"  # [not win]
    - "\"%R%\" -e \"library('inum')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=inum
  license: GPL-2
  summary: Enum-type representation of vectors and representation of intervals, including a method
    of coercing variables in data frames.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
