travis:
  secure:
    BINSTAR_TOKEN: 1R4MrlN+Rbk9eXd4Ia0gphiID01bOWdktiW9B3RsFs/uJ0c8iBNZf2Vc3ENOJOGlmQ9nVAKAssf0iQWQKpd0RVFj4tzi2O8X7aGyJJKWNDt4fiIv7cbMc5mjlU5eGLxosQkSw3O8nhJQ91vmaZZBO6PpXg4S4xr58FuOih5kNYzjIrQvwk+HfoVu2vWbgBTO/MTAUCizhAoECcJB04DblzQExJuro3im/rEFcqv2/ZBDTrRGfh6A44X/zEENwSuiy2VnNVown8G1V4uFD5VJYrLKk8OkNjpV0mcYZb7ZslR2LVt+mzWbu+aaketrOG+21d914MYT6ePeU5AWIUOQriPr6nx2+4JtFLtjbdsHacvKfOTzbxOj/SEA0lT6AnaniLFRfTv5lnSfIAjNoKuSkLzBdQQpn3uegcI+aBgJRDF74dA/wuVbrgR+JJoxTVo+A8hKxLOrV5gC88Fw0DZeVEAqhjRXqjPkKfpwIMA79ZHdq6JNLE/xlP+hNiZj+589wAtP5zs+AeNwcoIYqex80eGCsP5XVNRdar3XhYmPXEREauusgiIfbN8oQp/a5wQKvl64j5IY8XQTRms8lOXrF2SyAF/dPv/VQrNT7jNW/mTgbMwXwgL1gtVRvH5KizqX0Yj1RCYe8b2gtg+05LhY3pXYArQNycsVQH/3sLk7Ll0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
