travis:
  secure:
    BINSTAR_TOKEN: IrvLlyQL6cU6/UOlac0pEmCACrbhsg1tohMALKZEAOJ0ANXLgfLlmuQMumC9qiEKAMOFqLmF01uyvVC1Hw+ozNq3o1zkGhAoF9dvTNSXRDMOlB6OyTGWPG7VGdnMCkvKPE1X9w4Ds9KhaKFzcbLZHCtEVOHofC6LZHDN6wma9E7ZF29DxlxJ2XwtrU2Yz9vvCrJ6Sdn0mlrdQYUZGGbK6upW7r7XTOHmxtE+xrZAzeD+CAMnNR5cbwMhPE3fRrN/V6m7eQPUQfPbRJSzaAj/jRr1h+3BjbnLVKrI8VNrlzG7DceA+te0WkL5MbhvdAHGq812uLJxcrBdYZQn1Ir3cu7QHAGBv040Gk7INRuKnZDcws2VqvdfQQqd2/tKdfiDRyjaA8WK23KeWjlIp2Ikt8at8YBkhp5j7KTMUQGuZN7fad+iTLFX/lwthN+VFYIbqHFDiBVCHR35KWy5IELHWPFp+0vnFe+a54zNBzOjjhrg+EHBFbjXxLAV7PwsvDtexmZWT2MSlK/GEgD9/f8jYSWom328ULNTEoz+kjFAE2DWaH/3OslLyk9kb+RyxxRsMkeopmKme1Ujm/RiBCowvwapmg1Vgrf9GtR/kzHVxqToLpVn/DPrG4J0hALNwdLe1ts8wpTY3bBiNrY4Lg8eGPNFbSXTLyE0R+tu5PpdI/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
