travis:
  secure:
    BINSTAR_TOKEN: cFrfo/3hS7J+PXJum1Ohh/+umZeHhhFCRMzj9PTTPR3aud7A7ZBzUQdcxtX3BYxdpXcMpeirUFGuWbCCWSKfdrfszvLbGjqHTNHFcMO0XGJwowNn/DTKP3gmo7kX7xlsXtscQVVm6e4eQgq90+44CzQNAe82ZbUGdwVPT73WIUMlZ6GY7vNv4Mr4kuGBP6kyz/8NV6CEUTM2h3qF8AxVaHEt2fiZT0jhFixP6BgjU7e01K859nlPOECV6yDCzjZKRIQCYwcRkykEGHCCsNjEWjsMtmIARB/zt7S1BxQrws7dtFNlFjCiV/B5LR2Qe0xOx/+dlJ5zqbULi6xx7+6fWHVefvd0YmefMRyMZrT61vIs4gCLJ+pphnQ1uFxfvxgOGuujwgYdCejV8fIcPzeVEiVTDJmxIQP2ADRFeSIagZhJBjnkQDl9DifLdzeb0BluWm97xTXJ7a7FDK+LjE5k3su5t6dLdWFm7DUOJA+1HyfOGte96qWkJZNXPYpDaPiy7b3J2RsM0QR51xti/1xi4fTW+n8YA1PbXHVk9PAvHoiUeHIqu3TwgoOOjrA2nGjPAbi3ait/oPUvI5CFzi5jrRVeQPSZ7nx7c+5rdZpfD8Hi/pJfw3PTTrv0z1UoCTP9xh/DDQuVBuYEuPcVQzGqGf26+RebTh31zzqWDvk58yA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
