travis:
  secure:
    BINSTAR_TOKEN: jCtYcuJHq8JthGE6s19H6yWuu8jewYfM+DQJBWYgiD/F+nOCxJc49HZyFEIIIpUMt9nA7MVrmb0jko0cixotwYE0LYZhxC366sTGsUObqK/Sy9xFYjyry7lOHexTe9HAYq9K6cveblqJqrSAIeAmtD2EDk/a0rkccN79I0L+x24IGuHuzM+b/hYSy5hqUy4HeUzpP+xz88y8vstUTn/HPv54SItREnh7xxNZNSD4YJ6dN8Oa0LG152rm8BZhEiuXSA2PZvCrCKtuieMyWPHXmcZgA9v895uEzQ/8sKUDSZ0AGIVA9cOTyTyqqLaZBTSewPFNpfxjQHP2ppKfwcM76zn3egl/8KTYDTuzUVkkkUuOA1zyarNUov0UzLfvL53QZR+UQZZMDU1cTeN3eu1+RVhNHL57Z6poaKZ6Ijars/UIbhTV+RBOz195tNa9D2S06eaDSW5r48j6CKfsY28U8KORdpctdfjPezFwh/YDDZauLtFBug4QBAhAs+vCBFfFr9jbEucLt29R6gzs/mLcEE5GIiFem7XiqDJ+hEIwv55nefyMxvcTOwTWetFf6J+6cWOjhqc3XYL3m0vMfMEc6CWTAxbIcTfMudxYWXBpsOF1zd1vKKOWsD7duIZbbhrx2p/nmwqqVStfK8pJjB30cJMhqj4AUQ1OM1af83jxA4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
